name: Scrape
on:
  # TODO: manually trigger with minute as input
  push:
  schedule:
  - cron: '* * * * *' # continuous
  #- cron: '12 3 * * *' # daily
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip install scrapy arrow
      # TODO: figure out last time workflow was run vs hardcoding 60 min
      - run: scrapy runspider scrape.py -O updates.json -a minutes=60
      - run: python merge.py
      - uses: EndBug/add-and-commit@v8
        id: commit
        with:
          default_author: user_info
          message: 'Update Field Notes tracked website data'
          add: 'results.json'
      - uses: ethomson/send-tweet-action@v1
        if: steps.commit.outputs.committed == 'true'
        with:
          status: "An update has been detected on the Field Notes website! https://github.com/fieldnotesradar/FieldNotesScraper/commit/${{ steps.commit.outputs.commit_long_sha }}"
          consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}