name: Scrape
on:
  workflow_dispatch:
    inputs:
      range:
        description: 'Lookback range in minutes'
      tweet:
        description: 'Allow Tweet if changes are detected'
        default: false
        type: boolean
  schedule:
  - cron: '* * * * *' # continuous
  - cron: '12 3 * * *' # daily
env:
  RANGE: ${{ github.event.inputs.range }}
  TWEET: ${{ github.event.inputs.tweet || true }}
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - run: echo "RANGE=" >> $GITHUB_ENV
        if: github.event.schedule == '12 3 * * *'
      # TODO: set range to last time workflow ran
      - run: echo "RANGE=60" >> $GITHUB_ENV
        if: github.event.schedule == '* * * * *'
      - uses: actions/checkout@v2
      - run: pip install scrapy arrow
      - run: scrapy runspider scrape.py -O updates.json -a minutes=$RANGE
      - run: python merge.py
      - uses: EndBug/add-and-commit@v8
        id: commit
        with:
          message: 'Update tracked Field Notes website data'
          add: 'results.json'
      - uses: ethomson/send-tweet-action@v1
        if: ${{ steps.commit.outputs.committed != 'undefined' && env.TWEET == 'true' }}
        with:
          status: "An update has been detected on the Field Notes website! https://github.com/fieldnotesradar/FieldNotesScraper/commit/${{ steps.commit.outputs.commit_long_sha }}"
          consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}