name: Scrape
on:
  push:
  schedule:
  - cron: "* * * * *"
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip install scrapy
      - run: scrapy runspider scrape.py -o raw.json
      - run: cat raw.json | jq 'sort_by(.item)' > data.json
      - uses: EndBug/add-and-commit@v8
        id: commit
        with:
          default_author: user_info
          message: 'Updated Field Notes product list'
          add: 'data.json'
      - uses: ethomson/send-tweet-action@v1
        if: steps.commit.outputs.committed == 'true'
        with:
          status: "Field Notes product list has been updated! https://github.com/fieldnotesradar/FieldNotesScraper/commit/${{ steps.commit.outputs.commit_long_sha }}"
          consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}